### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by eagle2014** [nhattruongniit/react-boilerplate-material#2]
when we have build or run npm start so that we can received 1 error at the NavBar  in the Style.ts file.

" 
Types of property 'fontWeight' are incompatible.
              Type 'FontWeight | undefined' is not assignable to type 'FontWeightProperty | PropsFunc<{}, FontWeightProperty | undefined> | undefined'.
                Type 'string & {}' is not assignable to type 'FontWeightProperty | PropsFunc<{}, FontWeightProperty | undefined> | undefined'.
                  Type 'string & {}' is not assignable to type '"lighter"'.
"

pls help me to check it.

**Comment by nhattruongniit** [comment]
I fixed it. Thank for report.

**Comment by nhattruongniit** [comment]
Hi Eagle 2014,

I fixed it. Thank for report.

Best regards,
